scalar Unknown
scalar DateTime
scalar Address
scalar AttachmentRef
scalar Amount_Tokens
scalar EthereumAddress
scalar EmailAddress
scalar Amount_Percentage
scalar Date
scalar URL
scalar Amount_Money
scalar OLabel
scalar Currency
scalar PHID
scalar OID
scalar Amount_Fiat
scalar Amount_Currency
scalar Amount_Crypto
scalar Amount
scalar Upload

type InvoiceState {
  status: Status!
  invoiceNo: String!
  dateIssued: Date
  dateDue: Date
  dateDelivered: Date
  issuer: LegalEntity!
  payer: LegalEntity!
  currency: String!
  lineItems: [InvoiceLineItem!]!
  totalPriceTaxExcl: Float!
  totalPriceTaxIncl: Float!
  notes: String
  rejections: [Rejection!]!
  payments: [Payment!]!
  payAfter: DateTime
  invoiceTags: [InvoiceTag!]!
  exported: ExportedData!
  closureReason: ClosureReason
  baseInvoice: AttachmentRef
  timeTrackingReport: AttachmentRef
}

enum ClosureReason {
  UNDERPAID
  OVERPAID
  CANCELLED
}

type Rejection {
  id: OID!
  reason: String!
  final: Boolean!
}

type ExportedData {
  timestamp: DateTime
  exportedLineItems: [[String!]!]!
}

type Payment {
  id: OID!
  processorRef: String
  paymentDate: DateTime
  txnRef: String
  confirmed: Boolean!
  issue: String
  amount: Float
}

type Token {
  evmAddress: String
  symbol: String
  chainName: String
  chainId: String
  rpc: String
}

type LegalEntity {
  id: LegalEntityId
  name: String
  address: InvoiceAddress
  contactInfo: ContactInfo
  country: String
  paymentRouting: PaymentRouting
}

type InvoiceAddress {
  streetAddress: String
  extendedAddress: String
  city: String
  postalCode: String
  country: String
  stateProvince: String
}

type ContactInfo {
  tel: String
  email: String
}

type PaymentRouting {
  bank: Bank
  wallet: InvoiceWallet
}

type Bank {
  name: String!
  address: InvoiceAddress!
  ABA: String
  BIC: String
  SWIFT: String
  accountNum: String!
  accountType: InvoiceAccountType
  beneficiary: String
  intermediaryBank: IntermediaryBank
  memo: String
}

type IntermediaryBank {
  name: String!
  address: InvoiceAddress!
  ABA: String
  BIC: String
  SWIFT: String
  accountNum: String!
  accountType: InvoiceAccountType
  beneficiary: String
  memo: String
}

type InvoiceWallet {
  rpc: String
  chainName: String
  chainId: String
  address: String
}

type InvoiceLineItem {
  id: OID!
  description: String!
  taxPercent: Float!
  quantity: Float!
  currency: String!
  unitPriceTaxExcl: Float!
  unitPriceTaxIncl: Float!
  totalPriceTaxExcl: Float!
  totalPriceTaxIncl: Float!
  lineItemTag: [InvoiceTag!]!
  receipts: [AttachmentRef!]!
}

type InvoiceTag {
  dimension: String!
  value: String!
  label: String
}

type LegalEntityId {
  taxId: String
  corpRegId: String
}

enum Status {
  DRAFT
  ISSUED
  CANCELLED
  ACCEPTED
  REJECTED
  PAYMENTSCHEDULED
  PAYMENTSENT
  PAYMENTISSUE
  PAYMENTRECEIVED
  PAYMENTCLOSED
}

enum InvoiceAccountType {
  CHECKING
  SAVINGS
  TRUST
  WALLET
}

enum InvoiceAccountTypeInput {
  CHECKING
  SAVINGS
  TRUST
  WALLET
}

# general

input EditInvoiceInput {
    invoiceNo: String
    dateIssued: String
    dateDelivered: String
    dateDue: String
    currency: String
    notes: String
}

input AddPaymentInput {
  id: OID!
  processorRef: String
  paymentDate: DateTime
  txnRef: String
  confirmed: Boolean!
  issue: String
}

input EditPaymentDataInput {
  id: OID!
  processorRef: String
  paymentDate: DateTime
  txnRef: String
  confirmed: Boolean!
  issue: String
}

input EditStatusInput {
  status: Status!
}

input SetExportedDataInput {
  timestamp: DateTime!
  exportedLineItems: [[String!]!]!
}

# parties

input EditIssuerBankInput {
    name: String
    streetAddress: String
    extendedAddress: String
    city: String
    postalCode: String
    country: String
    stateProvince: String
    ABA: String
    BIC: String
    SWIFT: String
    accountNum: String
    accountType: InvoiceAccountTypeInput
    beneficiary: String
    memo: String
    nameIntermediary: String
    streetAddressIntermediary: String
    extendedAddressIntermediary: String
    cityIntermediary: String
    postalCodeIntermediary: String
    countryIntermediary: String
    stateProvinceIntermediary: String
    ABAIntermediary: String
    BICIntermediary: String
    SWIFTIntermediary: String
    accountNumIntermediary: String
    accountTypeIntermediary: InvoiceAccountTypeInput
    beneficiaryIntermediary: String
    memoIntermediary: String
}

input EditIssuerInput {
    id: String
    name: String
    streetAddress: String
    extendedAddress: String
    city: String
    postalCode: String
    country: String
    stateProvince: String
    tel: String
    email: String
}

input EditIssuerWalletInput {
    rpc: String
    chainName: String
    chainId: String
    address: String
}

input EditPayerBankInput {
    name: String
    streetAddress: String
    extendedAddress: String
    city: String
    postalCode: String
    country: String
    stateProvince: String
    ABA: String
    BIC: String
    SWIFT: String
    accountNum: String
    accountType: InvoiceAccountTypeInput
    beneficiary: String
    memo: String
    nameIntermediary: String
    streetAddressIntermediary: String
    extendedAddressIntermediary: String
    cityIntermediary: String
    postalCodeIntermediary: String
    countryIntermediary: String
    stateProvinceIntermediary: String
    ABAIntermediary: String
    BICIntermediary: String
    SWIFTIntermediary: String
    accountNumIntermediary: String
    accountTypeIntermediary: InvoiceAccountTypeInput
    beneficiaryIntermediary: String
    memoIntermediary: String
}

input EditPayerInput {
    id: String
    name: String
    streetAddress: String
    extendedAddress: String
    city: String
    postalCode: String
    country: String
    stateProvince: String
    tel: String
    email: String
}

input EditPayerWalletInput {
    rpc: String
    chainName: String
    chainId: String
    address: String
}

# items

input AddLineItemInput {
    id: OID!
    description: String!
    taxPercent: Float!
    quantity: Float!
    currency: String!
    unitPriceTaxExcl: Float!
    unitPriceTaxIncl: Float!
    totalPriceTaxExcl: Float!
    totalPriceTaxIncl: Float!
}

input DeleteLineItemInput {
  id: OID!
}

input EditLineItemInput {
    id: OID!
    description: String
    taxPercent: Float
    quantity: Float
    currency: String
    unitPriceTaxExcl: Float
    unitPriceTaxIncl: Float
    totalPriceTaxExcl: Float
    totalPriceTaxIncl: Float
}

input SetInvoiceTagInput {
  dimension: String!
  value: String!
  label: String
}

input SetLineItemTagInput {
  lineItemId: OID!
  dimension: String!
  value: String!
  label: String
}

# transitions

input AcceptInput {
  payAfter: DateTime
}

input CancelInput {
  _empty: Boolean
}

input ClosePaymentInput {
  closureReason: ClosureReasonInput
}

enum ClosureReasonInput {
  UNDERPAID
  OVERPAID
  CANCELLED
}

input ConfirmPaymentInput {
  id: OID!
  amount: Float!
}

input IssueInput {
  invoiceNo: String!
  dateIssued: String!
}

input ReapprovePaymentInput {
  _empty: Boolean
}

input RegisterPaymentTxInput {
  id: OID!
  timestamp: DateTime!
  txRef: String!
}

input ReinstateInput {
  _empty: Boolean
}

input RejectInput {
  id: OID!
  reason: String!
  final: Boolean!
}

input ReportPaymentIssueInput {
  id: OID!
  issue: String!
}

input ResetInput {
  _empty: Boolean
}

input SchedulePaymentInput {
  id: OID!
  processorRef: String!
  paymentDate: DateTime
}

# attachments

input SetTimeTrackingReportInput {
  timeTrackingReport: AttachmentRef
}

input SetBaseInvoiceInput {
  baseInvoice: AttachmentRef
}

input AddLineItemReceiptInput {
  lineItemId: OID!
  receipt: AttachmentRef!
}

input RemoveLineItemReceiptInput {
  lineItemId: OID!
  receipt: AttachmentRef!
}